version: "3.7"

networks:
  dev:
    driver: bridge

services:
  postgres:
    image: postgres:12
    container_name: previzen-postgres
    restart: always
    networks:
      - dev
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${PREVIZEN_PASSWORD}
    ports:
      - 5432:5432
