version: "3.7"

networks:
  dev:
    driver: bridge

services:
  postgres:
    image: postgres:12
    container_name: previzen
    restart: always
    networks:
      - dev
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: previzen
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
